title: beschlagnahmt.org
author:
  name: ACAB
  email: info@beschlagnahmt.org
description: IT-Sicherheit f√ºr Aktivisti!
url: "https://beschlagnahmt.org"

minima:
  date_format: "%d.%m.%Y"
  skin: auto
  social_links:
    - title: beschlagnahmt.org auf GitHub
      icon: github
      url: "https://github.com/beschlagnahmt-org/beschlagnahmt"
    - title: beschlagnahmt.org bei Mastodon
      icon: mastodon
      url: "https://social.bau-ha.us/@beschlagnahmt"
  nav_pages:
    - _pages/0_about.md
    - _pages/1_themen.md
    - _pages/2_download.md
    - _pages/3_impressum-kontakt.md

# Build settings
source: .
markdown: kramdown
encoding: utf-8
theme: minima
plugins:
  - jekyll-paginate
#  - jekyll-srcset
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
keep_files:
  - assets
  - Font-Awesome
