title: beschlagnahmt.org
author:
  name: ACAB
  email: beschlagnahmt@riseup.net
description: IT-Sicherheit f√ºr Aktivisti!
url: https://beschlagnahmt.org

minima:
  date_format: "%d.%m.%Y"

  # generate social links in footer
  social_links:
    github:  beschlagnahmt-org
    mastodon:
      - username: beschlagnahmt 
        instance: social.bau-ha.us

# Build settings
source: .
markdown: kramdown
encoding: utf-8
theme: minima
plugins:
  - jekyll-paginate
#  - jekyll-srcset
  - jekyll-seo-tag
  - jekyll-sitemap
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
keep_files:
  - assets
header_pages:
 -  _pages/0_about.md
 -  _pages/1_themen.md
 -  _pages/2_download.md
 -  _pages/3_impressum-kontakt.md
