title: beschlagnahmt.org
author:
  name: ACAB
  email: beschlagnahmt@riseup.net
description: IT-Sicherheit für Aktivisti! Behörden können deine elektronischen Geräte beschlagnahmen, auslesen oder deine Kommunikation überwachen. Du kannst dafür sorgen, dass die ganze Aktion zwar nervig ist, aber der Staat nicht in deinen persönlichen Daten rumschnüffelt.

minima:
  date_format: "%d.%m.%Y"

  # generate social links in footer
  social_links:
    twitter: beschlagnahmt_
    github:  beschlagnahmt-org
    mastodon:
      - username: beschlagnahmt 
        instance: social.bau-ha.us

# Build settings
source: .
markdown: kramdown
encoding: utf-8
theme: minima
plugins:
  - jekyll-paginate
#  - jekyll-srcset
  - jekyll-seo-tag
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md
keep_files:
  - assets
header_pages:
 -  _pages/about.md
 -  _pages/themen.md
 -  _pages/download.md
 -  _pages/impressum-kontakt.md
